### ISSUE TITLE
Strict validation of `structs`

### ISSUE THREAD

**Issue by th0r** [gcanti/tcomb-validation#12]
Hi!
I've got one question: is it possible to strictly validate tcomb structs, so this will fail:
```js
validate(
    { a: 'ok', b: 'invalid extra prop' },
    struct({ a: Str })
); // => fail because of extra `b` prop
```

**Comment by gcanti** [comment]
Hi,

no, atm validations are "structural" (similar to what TypeScript does)

**Comment by th0r** [comment]
Got it. Thanks for the great lib!

**Comment by tehnomaag** [comment]
I know that tcomb-react does strict validation for props (see https://github.com/gcanti/tcomb-react/blob/master/index.js#L94). I've found this to super useful in React component development.

Just now I was writing a node express app config validation with tcomb/tcomb-validation, to make sure all runtime-loaded server configuration is proper and no app mis-configuration issues would slip by undetected. So this lib works great for stuff I've defined types for, but in this use-case it would be really nice to also do strict validation.

Perhaps you'll consider re-opening this issue and adding an optional strict validation mode, just like tcomb-react lib does?

**Comment by gcanti** [comment]
Hi @tehnomaag,

So a new option `strict: boolean` right?

**Example**

```js
import t from 'tcomb-validation'

const Point = t.struct({
  x: t.Number,
  y: t.Number
}, 'Point');

const result = t.validate({x: 1, y: 2, z: 3, k: 4}, Point, { strict: true })

console.log(JSON.stringify(result.errors, null, 2))
```

**Output**

```json
[
  {
    "message": "Invalid value 3 supplied to /z: Nil",
    "actual": 3,
    "path": [
      "z"
    ]
  },
  {
    "message": "Invalid value 4 supplied to /k: Nil",
    "actual": 4,
    "path": [
      "k"
    ]
  }
]
```

**Rationale**. Except `x` and `y`, additional properties should be `Nil`. Thus these are equivalent:

```js
t.validate({x: 1, y: 2}, Point, { strict: true }).isValid() // => true
t.validate({x: 1, y: 2, z: null}, Point, { strict: true }).isValid() // => true
t.validate({x: 1, y: 2, z: undefined}, Point, { strict: true }).isValid() // => true
```

**Comment by tehnomaag** [comment]
Yep, that looks exactly what I need. Also, the strict validation flag should propagate if the type is a nested structure, so even errors deeper in the value would be caught.

**Comment by gcanti** [comment]
Released in v2.3.0 https://github.com/gcanti/tcomb-validation/releases/tag/v2.3.0

**Comment by tehnomaag** [comment]
Thanks for the quick turnaround. Updated and using it now :)

**Comment by gcanti** [comment]
:+1:
