### ISSUE TITLE
Path in dict errors includes all keys upto the error.

### ISSUE THREAD

**Issue by jollytoad** [gcanti/tcomb-validation#15]
Example to reproduce (in the playground):

    var Dict = t.dict(Str, Str);
    validate({a: "a", b: "b", c: "c", d: 0}, Dict);

Error message:

> /a/b/c/d is `0` should be a `Str`

I'd expect it to just be:

> /d is `0` should be a `Str`

**Comment by gcanti** [comment]
Thanks @jollytoad
