### ISSUE TITLE
Brainstorming some ideas

### ISSUE THREAD

**Issue by ivan-kleshnin** [gcanti/tcomb-validation#16]
Hi Giulio!

I wrote a big article / proposition about validation here:
https://github.com/ansman/validate.js/issues/50

I think it should be interesting to you as well because Tcomb-validation has a lot of the same weaknesses as ValidateJs and Joi. No separate parsing step (e.g. no idiomatic way to decipher L10n of input data, no way to "jump through" formats (like splitting tags into array), etc.). You may answer there or here if you wish, I will pick up the discussion anyway.

**Comment by gcanti** [comment]
Hi Ivan,
I'm glad to see you again.
I'm going to read your article, thanks for pointing out.

p.s.
As you suggested 7 months ago, I'm digging into semantic ui for my tcomb-form project: great framework.
https://github.com/gcanti/tcomb-form/blob/master/src/templates/semantic.js

**Comment by ivan-kleshnin** [comment]
> I'm glad to see you again.

I'm suprised you remembered me :smile: 

> As you suggested 7 months ago, I'm digging into semantic ui for my tcomb-form project: great framework.

It changed very much since then. For better I believe. 

> I'm going to read your article, thanks for pointing out.

Yeah, I want to discuss this with someone experienced. Half-year ago I was super newbie in the frontend development. Now I've got some experience. I'm excited about your **tcomb** project but I wonder how well it suits for ideas I put in those article. 

I'm considering to create a library with described behavior on my own, but if it's possible to reuse or update **tcomb-validation** to cover those issue cases it will be much better. I'm not chasing the glory of library creator, I'm a practical man :wink:

**Comment by ivan-kleshnin** [comment]
I managed to combine Tcomb validation with proper I18n handliing and I'm pretty happy with results so forth. I'm going to write an article after some trial and post a link here.

**Comment by gcanti** [comment]
> I'm going to write an article after some trial and post a link here

Great! Looking forward to your post. 
Btw, for i18n, have you noticed this issue? https://github.com/gcanti/tcomb-validation/issues/27

**Comment by ivan-kleshnin** [comment]
> Btw, for i18n, have you noticed this issue?

Yes. My concerns were about lower level stuff like converting dates in string format to Date objects to make them possible to validate with Tcomb. I'm going to mess with validation messages customization a bit later :smile: Thank you!
