### ISSUE TITLE
How to deal w server side validation exceptions

### ISSUE THREAD

**Issue by mschipperheyn** [gcanti/tcomb-validation#19]
For instance, the password you entered passes validation but comes back from the server as incorrect.

So, now you want to manually create a validation exception against this password, perhaps even use the server side error message you got back, and update the UI accordingly. How do you do that?

**Comment by mschipperheyn** [comment]
In this sense (server side exception), it would also be nice to be able to show a general exception (that doesn't have a specific path). E.g. Your username or password doesn't match.

**Comment by gcanti** [comment]
tcomb-validation builds on tcomb and tcomb doesn't support subtypes defined by async predicates.
Async validations must be handled outside this lib at the moment

**Comment by mschipperheyn** [comment]
Yeah, that doesn't make any sense. The server side is an integral part of any application and not having a way to hook into the exception mechanisms of tcomb creates endless complications. What I would recommend is to add an "invalidate" method. 

    invalidate(type, pathObject);

The pathObject would specify the exception paths and allow for a general error message

    var pathObject = {
      error:"Please check the form below",
      fields:{
          password:{
            error: "Invalid password"
          }
      }      
    };

For example

    var Login = t.struct({
     email: t.Str,
     password: t.Str
    });

    //after validating and posting to the server a "password invalid" message comes back
    t.invalidate(Login,pathObject);

Conceivably, one single field could generate multiple exceptions

    var pathObject = {
      error:"Please check the form below",
      fields:{
          password:{
            error: ["has a minimum length of 10","Has to contain at least the following characters: $%_"]
          }
      }      
    };

I really hope you consider integrating this. It should be quite easy and it's simply necessary

**Comment by patte** [comment]
If you are actually using tcomb-form, this might help you: https://github.com/gcanti/tcomb-form/issues/234
