### ISSUE TITLE
Please fix dependencies

### ISSUE THREAD

**Issue by chasm** [gcanti/tcomb-validation#20]
207 error Darwin 14.4.0
208 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i" "--save" "tcomb-validation"
209 error node v2.3.3
210 error npm  v2.11.3
211 error code EPEERINVALID
212 error peerinvalid The package tcomb does not satisfy its siblings' peerDependencies requirements!
212 error peerinvalid Peer tcomb-validation@1.0.4 wants tcomb@^1.0.0
213 verbose exit [ 1, true ]

**Comment by gcanti** [comment]
Hi, 
Not sure what's the problem here (actually tcomb-validation@1.0.4 wants tcomb@^1.0.0),
Could you elaborate a little bit?

**Comment by chasm** [comment]
I tried to install tcomb, tcomb-form, tcomb-react, and tcomb-validation without specifying versions assuming I'd get the latest versions and they would play nice together. For some reason, tcomb-validation keep trying to install 1.0.4 instead of 2.0.0-beta, and as it was doing this after tcomb 2.0.0 had already installed, it threw this error. I worked around it by installing tcomb-validation separately and forcing it to 2.0.0-beta. Odd that it didn't just grab that version up front. Maybe because it's beta?

**Comment by gcanti** [comment]
> Maybe because it's beta

Ah..It's possible. Anyway I just released a new version of tcomb-validation, tcomb-form and tcomb-react pointing to latest versions of tcomb and tcomb-validation (respectively). It should be ok now. Let me know.

**Comment by chasm** [comment]
Excellent. Will do.

**Comment by chasm** [comment]
Worked well. Thank you much!
