### ISSUE TITLE
Empy list validation

### ISSUE THREAD

**Issue by steffenmllr** [gcanti/tcomb-validation#26]
I'm trying to validate a list of emails with t-comb forms and a custom factory (tags input)

It seems like an empty list does not get passed to the custom validation.
Is there a reason that an empty list is valid ? shouldn't only a `maybe` empty list be valid ?

```js
import email from 'email-validation';
import {validate} from 'tcomb-validation';
var t = require('tcomb-form');

let mailForm = t.list(t.subtype(t.Str, (s) => email.valid(s)));
let result = validate([], mailForm);
console.log(result.isValid()); // returns true for empty lists
```

**Comment by gcanti** [comment]
Hi,
No, an empty list (`[]`) is a valid list. The `maybe` combinator is useful when you want to accept also `null` and `undefined`.

```js
const Email = t.subtype(t.String, (s) => email.valid(s), 'Email');
const ListOfEmails = t.list(Email);
ListOfEmails([]); // => ok

// you may want a not empty list of emails
const NotEmptyListOfEmails = t.subtype(ListOfEmails, (l) => l.length > 0, 'NotEmptyListOfEmails');
NotEmptyListOfEmails([]); // => throws "[tcomb] Invalid value [] supplied to NotEmptyListOfEmails"
```

**Comment by steffenmllr** [comment]
That makes sense - thank you! Didn't know I could chain validations like that

**Comment by gcanti** [comment]
> Didn't know I could chain validations like that

You can chain the tcomb combinators (i.e. the validations) at your will, with arbitrary level of nesting.

p.s.
the `validate` function is re-exported  by the tcomb-form library

```js
import t, { validate } from 'tcomb-form';
```
