### ISSUE TITLE
Localization support in `getValidationErrorMessage`?

### ISSUE THREAD

**Issue by th0r** [gcanti/tcomb-validation#27]
Hi and thanks for the great lib!

I have one question though: what is the proper way to return localized error messages from `getValidationErrorMessage` function?

The problem is I have to pass user's locale into this function somehow in order to return proper error message and the only solution I found now is to construct one struct per locale (but I don't like it):

```js
// ./structs/ShortString.js

const _ = require('lodash');
const t = require('tcomb');

const intl = require('./intl');

module.exports = _.memoize(locale => {
    const ShortString = t.subtype(t.String, s => s.length < 3);

    ShortString.getValidationErrorMessage = value => {
        if (!value) {
            return intl(locale, 'Required');
        }

        if (value.length >= 3) {
            return intl(locale, 'Too long my friend');
        }
    };

    return ShortString;
});

// Some Express.js middleware
const ShortString = require('./structs/ShortString');

app.use((req, res) => {
    const locale = getUserLocale(req);
    
    const validationResult = validate(req.query.str, ShortString(locale));
});
```

The other solution could be is to pass an external `options` (or `context`) argument to `validate()`.
Then this example would look like this:
```js
// ./structs/ShortString.js

const _ = require('lodash');
const t = require('tcomb');

const intl = require('./intl');

const ShortString = t.subtype(t.String, s => s.length < 3);

ShortString.getValidationErrorMessage = (value, context) => {
    const { locale } = context;
    
    if (!value) {
        return intl(locale, 'Required');
    }

    if (value.length >= 3) {
        return intl(locale, 'Too long my friend');
    }
};

module.exports = ShortString;

// Some Express.js middleware
const ShortString = require('./structs/ShortString');

app.use((req, res) => {
    const locale = getUserLocale(req);
    
    const validationResult = validate(req.query.str, ShortString, { locale });
});
```

What do you think about it?

**Comment by gcanti** [comment]
Hi,
the current signature is

```js
validate(value, type, [path]) -> ValidationResult
```

What about replacing the `path` argument with a `context` argument?

```js
validate(value, type, [context]) -> ValidationResult
```

- `value` the value to validate
- `type` a type defined with the [tcomb](https://github.com/gcanti/tcomb) library
- `context` (optional) passed in to `getValidationErrorMessage` (useful for i18n)

where `getValidationErrorMessage` will have the following signature:

```js
getValidationErrorMessage(value, path, context)
```

**Note**. 

- `context` can be an array (as path prefix) for backward compatibility
- if an object, it can contain a `path` key that will be used as path prefix.

**Comment by th0r** [comment]
@gcanti The only concern I have is that `path` is an option, while `context` values are not.
So, maybe something like this?
```
validate(value, type, [options]) -> ValidationResult
```
`options` (optional) is an object with the following keys:
 - `path` - path prefix for validation
 - `context` - passed to `getValidationErrorMessage` (useful for i18n)

`options` can be a an array (as `path` prefix) for backward compatibility

**Comment by gcanti** [comment]
:+1:

**Comment by gcanti** [comment]
Just published v2.2.0 https://github.com/gcanti/tcomb-validation/releases/tag/v2.2.0
Let me know if everything's ok
Giulio

**Comment by th0r** [comment]
@gcanti Incredible speed, man! Thanks!

**Comment by th0r** [comment]
@gcanti It would be great to add context support to `tcomb-form`.

**Comment by gcanti** [comment]
@th0r https://github.com/gcanti/tcomb-form/issues/197
