### ISSUE TITLE
Cross validation question

### ISSUE THREAD

**Issue by patgod85** [gcanti/tcomb-validation#35]
Hello
I have found an issue #29 that partially answers my question.

I have a form

```javascript
var crossValidation = function(p){

    var regexp;
    
    switch(p.document_type){
        case 2: // Birth certificate
            regexp = /^\w+[А-Я]{2}\d{6}$/;
            break;
        case 4: // Seaman's discharge book
            regexp = /^[\d\w]{2}\d{7}$/;
            break;
    }

    return regexp.test(value);
};

var Person = t.subtype(
    t.struct({
        document_type: t.Number,
        document_number: t.String
    }),
    crossValidation
);
```
I need to mark as invalid **only** field "Document number" but not the whole form. Is there a way to implement it?

**Comment by gcanti** [comment]
> I need to mark as invalid only field "Document number" but not the whole form. Is there a way to implement it?

Hi,
Not sure I'm follow. It's a tcomb-validation or tcomb-form issue?

**Comment by patgod85** [comment]
I think it's more related to tcomb-form. Should I repost it there?

**Comment by gcanti** [comment]
Yes please. Anyway, could this issue be helpful for your use case? https://github.com/gcanti/tcomb-form/issues/233
