### ISSUE TITLE
Async validation support ?

### ISSUE THREAD

**Issue by singggum3b** [gcanti/tcomb-validation#46]
Hi @gcanti , tcomb validation is really great (helped so much in sharing validation code on different environment & write code in an understandable manner).
One missing feature though is the ability to do async validation.
Any plan to add this feature ?

**Comment by chirag04** [comment]
My 2 cents: I'm switching to tcomb-validation for client side validation because it's validation api is synchronous. I do need async-validation in my form stuff but that's outside the scope of this lib.

**Comment by gcanti** [comment]
Hi @singggum3b, I agreee with @chirag04, async validation is hard to integrate and is outside the scope of this lib
