### ISSUE TITLE
allow casting schema

### ISSUE THREAD

**Issue by chirag04** [gcanti/tcomb-validation#47]
```
var Point = t.struct({
  x: t.Number,
  y: t.Number
});
```

`validate({x: 0, y: 0, z: 0}, Point)`

Validation Result will skip `z: 0` right now. Which is exactly what i want but without running the validations. given an input and a schema, cast the input based on schema.

tcomb-validations is already doing the casting when validating the input. If we can expose this casting as a function which would just cast and not run the validations. 

Something like `cast({x: 0, y: 0, z: 0}, Point)` ruturns the `{ x: 0, y: 0 }` and not run the validations.

**Comment by gcanti** [comment]
`tcomb-validation` builds on `tcomb`, just call the `Point` constructor

```js
import t from 'tcomb-validation'

const Point = t.struct({
  x: t.Number,
  y: t.Number
})

console.log(Point({x: 0, y: 0, z: 0})) // Struct {x: 0, y: 0}
```

**Comment by chirag04** [comment]
nice. that mostly works but it's not actually casting tho. if my x,y are t.String, i still get them as Number. so it's not really casting the input (number) to schema type (string).

```
import t from 'tcomb-validation'

const Point = t.struct({
  x: t.String,
  y: t.String
})

console.log(Point({x: 0, y: 0, z: 0})) // Struct {x: 0, y: 0}
```

**Comment by gcanti** [comment]
Ah, so you mean `cast` in that sense. Actually you get a type error

```
TypeError: [tcomb] Invalid value 0 supplied to Struct{x: String, y: String}/x: String
```

Casting values to different types is against the very rationale of these libraries
