### ISSUE TITLE
subtype documentation missing

### ISSUE THREAD

**Issue by chirag04** [gcanti/tcomb-validation#48]
cc @gcanti

**Comment by gcanti** [comment]
What do you mean? There is https://github.com/gcanti/tcomb-validation#refinements

**Comment by chirag04** [comment]
Link in readme for subtype is broken. Not sure what's the difference between. Subtype and refinement.

**Comment by gcanti** [comment]
Oh! My bad, `subtype` is the old alias of `refinement` (now deprecated). I'll update the readme, thanks for pointing out
