### ISSUE TITLE
[rfc] ValidationError: relax message type

### ISSUE THREAD

**Issue by pigoz** [gcanti/tcomb-validation#53]
Hi Giulio!

Currently I am returning i18n keys from `getValidationErrorMessage` inside my application. I'd like to return an object instead so that I can use it as props for `react-intl`'s `<FormattedMessage>` component.

For this reason I'd like to change https://github.com/gcanti/tcomb-validation/blob/master/index.js#L9 from `t.String` to `t.Any`.

By doing this I can avoid my validation code to be coupled to `react-intl` or any other future i18n mechanism, and I don't need any special code to handle dynamic locale changes.

Please let me know your opinion on this!

**Comment by gcanti** [comment]
Agreed
