### ISSUE TITLE
[question] Extra value in error.paths array

### ISSUE THREAD

**Issue by davidchase** [gcanti/tcomb-validation#69]
Hi 👋 big fan of tcomb and just started exploring this lib for validation.

Had a question when I have this setup:

```js
const betterString = t.refinement(t.String, x => x !== '', 'BetterString')

const State = t.struct({
  state: betterString,
  code: t.maybe(t.Number)
}, {name:'State'})

const Code = t.struct({
  code: t.Number,
  state: t.maybe(t.String)
}, {name:'Code'})

const Union = t.union([State, Code], 'StateOrCode')

Union.dispatch = (obj) => {
  return betterString.is(obj['state']) ? State : Code
}

const data = {
  '32897284': {
    state: '',
    code: null
  }
}
```
which basically i want either state or code to be filled, both being filled is ok as well otherwise its an erorr
everything works great with this setup however in the `errors.path` i get the following `['32897284', 1, 'code']` not sure
why i need that number `1` in there.

i tracked the code down to [Line 223](https://github.com/gcanti/tcomb-validation/blob/master/index.js#L223) which concats an index with the paths
but im not sure i follow the logic for this to be in the paths array and was hoping for some insight

is this a bug or works as expected?

**Comment by gcanti** [comment]
The path is saying: there's an error related to the dictionary key `"32897284"`, its value should be of type `Code` (the second union member), but is not because the value of `"code"` is wrong

- dictionary key: `"32897284"`
- union member index: `1`
- struct key: `"code"`

**Comment by davidchase** [comment]
@gcanti thanks for the quick response, now it makes sense it just wasnt as obvious because i didnt know what to with that number..
